### ISSUE TITLE
Cannot change item id to a tool eg. golden_hoe

### ISSUE THREAD

**Issue by CallMeVorex** [MajesticFaucet/CondenserWand#1]
When changing 'item-name' to golden_hoe or 294 (the item id) i get an internal error and the console gets filled, as soon as i switch it back to 'STICK' works perfectly fine, tried putting golden_hoe in "" & '' same with the item id, does not work. Please could this get fixed as soon as :)

**Comment by MajesticFaucet** [comment]
It's GOLD_HOE

**Comment by MajesticFaucet** [comment]
Added https://github.com/MajesticFaucet/CondenserWand/commit/ac4ef41d8b155f14f593cac3e2701ecab7eee75b and https://github.com/MajesticFaucet/CondenserWand/commit/37283ae2b4c012ccce1ec7bac1ac921e7abeb67c which changes material parsing to allow lowercase letters and prevent spamming console/anvil sound looping on failure.
